---
title: "STAT414_Project"
authors: "Franchesca Garcia and Isha Nayak"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}

library(tidyverse)
library(lme4)
library(performance)
library(ggplot2)
library(ggeffects)
library(car)
library(emmeans)

```

```{r reading in data}

daly <- readxl::read_xlsx("dementia_data/daly.xlsx")
daly <- daly[15:20,]

overweight <- read_csv("dementia_data/overweight.csv")
obesity <- read_csv("dementia_data/obesity.csv")
inactivity <- read_csv("dementia_data/inactivity.csv")
hypertension <- read_csv("dementia_data/hypertension.csv")
alcohol <- read_csv("dementia_data/alcohol.csv")

```

```{r data cleaning}

# extracting the values we are interested in
# grand mean centering

daly <- daly |>
  pivot_longer(cols = 2:186, names_to = "country", values_to = "DALY") |>
  mutate(cenDALY = DALY - mean(DALY))

overweight <- overweight |>
  filter(Dim1 == "Both sexes") |>
  select(Location, Period, FactValueNumeric) |>
  rename(country = Location, year = Period, overweight = FactValueNumeric) |>
  mutate(cenOverweight = overweight - mean(overweight))

obesity <- obesity |>
  select(ParentLocation, Location, FactValueNumeric, Period) |>
  rename(region = ParentLocation, country = Location, year = Period, obesity = FactValueNumeric) |>
  mutate(cenObesity = obesity - mean(obesity))

inactivity <- inactivity |>
  select(Location, FactValueNumeric, Period) |>
  rename(country = Location, year = Period, inactivity = FactValueNumeric) |>
  mutate(cenInactivity = inactivity - mean(inactivity))

hypertension <- hypertension |>
  filter(Dim1 == "Both sexes",
        IndicatorCode == "NCD_HYP_PREVALENCE_A") |>
  select(Location, FactValueNumeric, Period) |>
  rename(country = Location, year = Period, hypertension = FactValueNumeric) |>
  mutate(cenHypertension = hypertension - mean(hypertension))

alcohol <- alcohol |>
  select(Location, FactValueNumeric, Period) |>
  rename(country = Location, year = Period, alcohol = FactValueNumeric) |>
  mutate(cenAlcohol = alcohol - mean(alcohol, na.rm = TRUE))

```

```{r data cleaning}

# joining data into one dataframe

alzheimers <- daly |>
  inner_join(overweight, by = c("year", "country")) |>
  inner_join(obesity, by = c("year", "country")) |>
  inner_join(inactivity, by = c("year", "country")) |>
  inner_join(hypertension, by = c("year", "country")) |>
  inner_join(alcohol, by = c("year", "country")) |>
  
  # removing South Sudan because it is missing values for Alcohol
  filter(country != "South Sudan") |>
    
  # grand mean centering Year now that all values are in one dataframe
  mutate(cenYear = year - mean(year)) |>
  
  # log transformation on DALY b/c of nonlinear trend
  mutate(logDALY = log(DALY)) |>
  mutate(cenLogDALY = logDALY - mean(logDALY)) 

```

```{r visual data exploration}

# matrix plot
pairs(alzheimers[, c("cenLogDALY", 
                     "cenYear",
                     "cenAlcohol", 
                     "cenHypertension", 
                     "cenInactivity",
                     "cenObesity",
                     "cenOverweight")],
      cex = 0.2)

```


```{r visual data exploration}

# assigning colors to Regions
region_colors <- c(
  "Africa" = "#9B59B6", 
  "Americas" = "#FF6347",
  "Eastern Mediterranean" = "#FFD700",
  "Europe" = "#4682B4",
  "South-East Asia" = "#228B22",
  "Western Pacific" = "#40E0D0"
)



# scatter plot of DALY by Alcohol
alzheimers |>
  ggplot() +
    geom_point(aes(x = alcohol, y = DALY, colour = region),
                alpha = 1, stroke = FALSE, size = 1.5) +
    scale_color_manual(values = region_colors) + 
    theme_minimal() +
    labs(title = "DALY due to Dementias by Alcohol",
         x = "Prevalence of heavy episodic drinking (%)",
         y = "DALY (years per capita)",
         colour = "Region", 
         linetype = "Region") 

# scatter plots of DALY by Alcohol separated by Region
alzheimers |>
  ggplot() +
    geom_point(aes(x = alcohol, y = DALY, colour = region),
                alpha = 1, stroke = FALSE, size = 1, show.legend = FALSE) +
    scale_color_manual(values = region_colors) + 
    facet_wrap(~ region) + 
    theme_minimal() +
    labs(title = "DALY due to Dementias by Alcohol",
         x = "Prevalence of heavy episodic drinking (%)",
         y = "DALY (years per capita)",
         colour = "Region", 
         linetype = "Region") 



# scatter plot of DALY by Obesity
alzheimers |>
  ggplot() +
    geom_point(aes(x = obesity, y = DALY, colour = region),
                alpha = 1, stroke = FALSE, size = 1.5) +
    scale_color_manual(values = region_colors) + 
    theme_minimal() +
    labs(title = "DALY due to Dementias by Obesity",
         x = "Prevalence of obesity (%)",
         y = "DALY (years per capita)",
         colour = "Region", 
         linetype = "Region") 

# scatter plots of DALY by Obesity seperated by Region
alzheimers |>
  ggplot() +
    geom_point(aes(x = obesity, y = DALY, colour = region),
                alpha = 1, stroke = FALSE, size = 1, show.legend = FALSE) +
    scale_color_manual(values = region_colors) + 
    facet_wrap(~ region) + 
    theme_minimal() +
    labs(title = "DALY due to Dementias by Obesity",
         x = "Prevalence of obesity (%)",
         y = "DALY (years per capita)",
         colour = "Region", 
         linetype = "Region") 

```

```{r visual data exploration}

# scatter plot of DALY by Region
DALY_means <- alzheimers |>
  group_by(region) |>
  summarise(mean_DALY = mean(DALY, na.rm = TRUE))

alzheimers |>
  ggplot() +
    geom_point(aes(x = region, y = DALY, color = region), alpha = 0.4, show.legend = FALSE) +
    geom_point(data = DALY_means, aes(x = region, y = mean_DALY), show.legend = FALSE, color = "black") +
    scale_color_manual(values = region_colors) +
    theme_minimal() +
    labs(title = "DALY due to Dementias by Region",
         x = "Region",
         y = "DALY (years per capita)") 



# scatter plot of Alcohol by Region
alcohol_means <- alzheimers |>
  group_by(region) |>
  summarise(mean_Alcohol = mean(alcohol, na.rm = TRUE))

alzheimers |>
  ggplot() +
    geom_point(aes(x = region, y = alcohol, color = region), alpha = 0.4, show.legend = FALSE) +
    geom_point(data = alcohol_means, aes(x = region, y = mean_Alcohol), show.legend = FALSE, color = "black") +
    scale_color_manual(values = region_colors) +
    theme_minimal() +
    labs(title = "Alcohol by Region",
         x = "Region",
         y = "Prevelance of episodic drinking (%)") 



# scatter plot of Obesity by Region
obesity_means <- alzheimers |>
  group_by(region) |>
  summarise(mean_Obesity = mean(obesity, na.rm = TRUE))

alzheimers |>
  ggplot() +
    geom_point(aes(x = region, y = obesity, color = region), alpha = 0.4, show.legend = FALSE) +
    geom_point(data = obesity_means, aes(x = region, y = mean_Obesity), show.legend = FALSE, color = "black") +
    scale_color_manual(values = region_colors) +
    theme_minimal() +
    labs(title = "Obesity by Region",
         x = "Region",
         y = "Prevelance of Obesity (%)") 



# scatter plot of DALY by Country
#alzheimers |>
#  ggplot() +
#    geom_point(aes(x = country, y = DALY, color = region), 
#        show.legend = FALSE, label = FALSE) +
#    scale_color_manual(values = region_colors) +
#    theme_minimal() +
#    labs(title = "DALY due to Dementias by Country",
#         x = "Country",
#         y = "DALY (years per capita)") 

```

```{r grouping variable exploration}

# exploring variation between Countries (Level 2) 
modelCountryOLS <- lm(cenLogDALY ~ country, data = alzheimers)
anova(modelCountryOLS)

```

```{r null model}

# null model with random effect of Country
model0Country <- lmer(cenLogDALY ~ (1 | country), data = alzheimers)
summary(model0Country)
performance(model0Country)
logLik(model0Country)

```

```{r}

# exploring fixed effects and crosslevel interactions

# adding Level 1 variables
model1a <- lmer(cenLogDALY ~ cenYear + cenAlcohol + cenObesity + (1 | country), data = alzheimers)
summary(model1a)
anova(model0Country, model1a)

# adding Region (Level 2 variable)
model1b <- lmer(cenLogDALY ~ cenYear + cenAlcohol + cenObesity + region + (1 | country), data = alzheimers)
summary(model1b)
anova(model1a, model1b)

# adding interaction between Obesitiy and Region
model1c <- lmer(cenLogDALY ~ cenYear + cenAlcohol + cenObesity*region + (1 | country), data = alzheimers)
summary(model1c)
anova(model1b, model1c)

# removing Alcohol, adding interaction between Alcohol and Region
# FINAL MODEL
model1d <- lmer(cenLogDALY ~ cenYear + cenAlcohol:region + cenObesity*region + (1 | country), data = alzheimers)
summary(model1d)
anova(model1c, model1d)

```

```{r}

final_model <- model1d

summary(final_model)
performance(final_model)
logLik(final_model)
anova(model0Country, final_model)

```

```{r diagnostic analysis}

par(mfrow = c(1, 3))  

# Residuals vs Fits
plot(fitted(final_model), residuals(final_model), main = "Residuals vs Fitted Values", xlab = "Fitted Values", ylab = "Residuals")


# QQ Plot
qqnorm(residuals(final_model))
qqline(residuals(final_model), col = "red")

# Histogram
hist(residuals(final_model), main = "Histogram of Residuals", xlab = "Residuals")

par(mfrow = c(1, 1))



# Interaction Plot for Alcohol
predicted_Ainteraction <- ggpredict(final_model, terms = c("cenAlcohol", "region"))
plot(predicted_Ainteraction) +
  scale_color_manual(values = region_colors) + 
  scale_fill_manual(values = region_colors) +
  labs(title = "Association between ln(DALY) and Alcohol",
       x = "Prevalence of heavy episodic drinking (%)",
       y = "Estimated ln(DALY) (years per capita)") +
  theme_minimal()

# Back-transformed
predicted_Ainteraction$predicted <- exp(predicted_Ainteraction$predicted);
predicted_Ainteraction$conf.low <- exp(predicted_Ainteraction$conf.low); predicted_Ainteraction$conf.high <- exp(predicted_Ainteraction$conf.high);
plot(predicted_Ainteraction) +
  scale_color_manual(values = region_colors) + 
  scale_fill_manual(values = region_colors) +
  labs(title = "Association between DALY and Alcohol",
       x = "Prevalence of heavy episodic drinking (%)",
       y = "Estimated DALY (years per capita)") +
  theme_minimal()



# Interaction Plot for Obesity
predicted_Ointeraction <- ggpredict(final_model, terms = c("cenObesity", "region"))
plot(predicted_Ointeraction) +
  scale_color_manual(values = region_colors) + 
  scale_fill_manual(values = region_colors) +
  labs(title = "Association between ln(DALY) and Obesity",
       x = "Prevalence of obesity (%)",
       y = "Estimated ln(DALY) (years per capita)") +
  theme_minimal()

# Back-transformed
predicted_Ointeraction$predicted <- exp(predicted_Ointeraction$predicted);
predicted_Ointeraction$conf.low <- exp(predicted_Ointeraction$conf.low); predicted_Ointeraction$conf.high <- exp(predicted_Ointeraction$conf.high);
plot(predicted_Ointeraction) +
  scale_color_manual(values = region_colors) +
  scale_fill_manual(values = region_colors) +
  labs(title = "Association between DALY and Obesity",
       x = "Prevalence of obesity (%)",
       y = "Estimated DALY (years per capita)") +
  coord_cartesian(ylim = c(0, 20)) +
  theme_minimal()

```




```{r}

# plotting lines of Alcohol by Region
alcohol_trends <- emtrends(final_model, ~ region, var = "cenAlcohol")
alcohol_trends <- as.data.frame(alcohol_trends)
alcohol_trends$cenAlcohol.trend <- exp(alcohol_trends$cenAlcohol.trend)
alcohol_trends$lower.CL <- exp(alcohol_trends$lower.CL)
alcohol_trends$upper.CL <- exp(alcohol_trends$upper.CL)

ggplot(alcohol_trends, aes(x = region, y = cenAlcohol.trend)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.2) +
  coord_flip() +
  scale_x_discrete(limits = rev(levels(factor(alzheimers$region)))) +
  theme_minimal() +
  labs(title = "Estimated multiplicative change in DALY\nper percentage point increase in heavy episodic drinking",
       x = "Region",
       y = "Estimated Multiplicative Change")

# plotting lines of Obesity by Region
obesity_trends <- emtrends(final_model, ~ region, var = "cenObesity")
obesity_trends <- as.data.frame(obesity_trends)
obesity_trends$cenObesity.trend <- exp(obesity_trends$cenObesity.trend)
obesity_trends$lower.CL <- exp(obesity_trends$lower.CL)
obesity_trends$upper.CL <- exp(obesity_trends$upper.CL)

ggplot(obesity_trends, aes(x = region, y = cenObesity.trend)) +
  geom_point() +  
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.2) +
  coord_flip() +
  scale_x_discrete(limits = rev(levels(factor(alzheimers$region)))) +
  theme_minimal() +
  labs(title = "Estimated multiplicative change in DALY\nper percentage point increase in obesity",
       x = "Region",
       y = "Estimated Multiplicative Change")

```


