---
title: "STAT 414 Project"
subtitle: "Franchesca Garcia and Isha Nayak"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(nlme)
library(lme4)
library(performance)
```

```{r loading data}

# reading in data for each variable
daly <- readxl::read_xlsx("stat414_project_data/daly_dementia.xlsx")
alcohol <- read.csv("stat414_project_data/alcohol.csv")
bloodGlucose <- read.csv("stat414_project_data/bloodglucose_lvl2.csv")
cholesterol <- read.csv("stat414_project_data/cholesterol.csv")
depression <- read.csv("stat414_project_data/depression_lvl2.csv")
finePartMatter <- read.csv("stat414_project_data/fine_particulate_matter.csv")
hypertension <- read.csv("stat414_project_data/hypertension.csv")
physicalActivity <- read.csv("stat414_project_data/insufficient_physical_activity.csv")
obesity <- read.csv("stat414_project_data/obesity.csv")

```

```{r cleaning data}

# transforming DALY data to long format
daly <- daly |>
  pivot_longer(cols = 2:186, names_to = "country", values_to = "DALY") |>
  rename (year = Yeaer)

# selecting relevant columns for each variable's dataframe
alcohol <- alcohol |>
  select(ParentLocation, Location, Period, FactValueNumeric) |>
  rename(region = ParentLocation, country = Location, year = Period, alcohol = FactValueNumeric)

bloodGlucose <- bloodGlucose |>
  select(Location, FactValueNumeric) |>
  rename(country = Location, bloodGlucose = FactValueNumeric)

cholesterol <- cholesterol |>
  select(Location, Period, FactValueNumeric) |>
  rename(country = Location, year = Period, cholesterol = FactValueNumeric)
cholesterol$year[cholesterol$year == 2018] <- 2020

depression <- depression |>
  select(Location, FactValueNumeric) |>
  rename(country = Location, depression = FactValueNumeric)

finePartMatter <- finePartMatter |>
  select(Location, Period, FactValueNumeric) |>
  rename(country = Location, year = Period, PM2.5 = FactValueNumeric)
finePartMatter$year[finePartMatter$year == 2018] <- 2020

hypertension <- hypertension |>
  select(Location, Period, FactValueNumeric) |>
  rename(country = Location, year = Period, hypertension = FactValueNumeric) |>
  filter(year == c(2019, 2015, 2010))
hypertension$year[hypertension$year == 2019] <- 2020

obesity <- obesity |>
  select(Location, Period, FactValueNumeric) |>
  rename(country = Location, year = Period, obesity = FactValueNumeric)

physicalActivity <- physicalActivity |>
  select(Location, Period, FactValueNumeric) |>
  rename(country = Location, year = Period, inactivity = FactValueNumeric)


# combining dataframes
alzheimers <- daly |>
  inner_join(alcohol, by = c("year", "country")) |>
  inner_join(bloodGlucose, by = "country") |>
  inner_join(cholesterol, by = c("year", "country")) |>
  inner_join(depression, by = "country") |>
  inner_join(finePartMatter, by = c("year", "country")) |>
  inner_join(hypertension, by = c("year", "country")) |>
  inner_join(obesity, by = c("year", "country")) |>
  inner_join(physicalActivity, by = c("year", "country"))

```


```{r numerical data exploration}

#five number summary
fivenum(alzheimers$DALY)
sd(alzheimers$DALY)

#region means
region_means = 
  alzheimers |>
    group_by(region) |>
    summarize(region_daly = mean(DALY)) 
region_means

#region standard deviation
region_sd = 
  alzheimers |>
    group_by(region) |>
    summarize(region_daly = sd(DALY)) 



#summary output for alcohol on DALY
model_alcohol= 
  lm(alzheimers$DALY ~ alzheimers$alcohol)
summary(model_alcohol)

#summary output for bloodGlucose on DALY
model_bloodGlucose= 
  lm(alzheimers$DALY ~ alzheimers$bloodGlucose)
summary(model_bloodGlucose)
  
#summary output for cholesterol on DALY
model_cholesterol= 
  lm(alzheimers$DALY ~ alzheimers$cholesterol)
summary(model_cholesterol)

#summary output for depression on DALY
model_depression= 
  lm(alzheimers$DALY ~ alzheimers$depression)
summary(model_depression)

#summary output for PM2.5 on DALY
model_PM2.5 = 
  lm(alzheimers$DALY ~ alzheimers$PM2.5)
summary(model_PM2.5)

#summary output for hypertension on DALY
model_hypertension = 
  lm(alzheimers$DALY ~ alzheimers$hypertension) 
summary(model_hypertension)

#summary output for obesity on DALY
model_obesity = 
  lm(alzheimers$DALY ~ alzheimers$obesity)
summary(model_obesity)

#summary output for inactivity on DALY
model_inactivity = 
  lm(alzheimers$DALY ~ alzheimers$inactivity)
summary(model_inactivity)
```
```{r visual data exploration}
alzheimers |>
  filter(DALY < 2000) |>
  ggplot() +
    geom_point(aes(x = alcohol, y = DALY, colour = as.factor(year)))

alzheimers |>
  filter(DALY < 2000) |>
  ggplot() +
    geom_point(aes(x = bloodGlucose, y = DALY, colour = as.factor(year)))

alzheimers |>
  filter(DALY < 2000) |>
  ggplot() +
    geom_point(aes(x = cholesterol, y = DALY, colour = as.factor(year)))

alzheimers |>
  filter(DALY < 2000) |>
  ggplot() +
    geom_point(aes(x = depression, y = DALY, colour = as.factor(year)))

alzheimers |>
  filter(DALY < 2000) |>
  ggplot() +
    geom_point(aes(x = PM2.5, y = DALY, colour = as.factor(year)))

alzheimers |>
  filter(DALY < 2000) |>
  ggplot() +
    geom_point(aes(x = hypertension, y = DALY, colour = as.factor(year)))

alzheimers |>
  filter(DALY < 2000) |>
  ggplot() +
    geom_point(aes(x = obesity, y = DALY, colour = as.factor(year)))

alzheimers |>
  filter(DALY < 1000) |>
  ggplot() +
    geom_point(aes(x = inactivity, y = DALY, colour = as.factor(year)))

alzheimers |>
  filter(DALY < 1000) |>
  group_by(region) |>
  summarize(region_daly = mean(DALY, colour = as.factor(year))) |>
  ggplot() +
    geom_bar(aes(x = region, y = region_daly), stat = "identity")
```

